apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qliksense
resources:
  - audit
  - chronos
  - chronos-worker
  - collections
  - data-connector-odbc
  - data-connector-qwc
  - data-connector-rest
  - data-prep
  - data-rest-source
  - dcaas
  - dcaas-web
  - edge-auth
  - elastic-infra
  - encryption
  - engine
  - feature-flags
  - groups
  - hub
  - identity-providers
  - keys
  - licenses
  - locale
  - management-console
  - messaging
  - mongodb
  - odag
  - policy-decisions
  - qix-data-connection
  - qix-datafiles
  - qix-sessions
  - reporting
  - resource-library
  - sense-client
  - spaces
  - temporary-contents
  - tenants
  - users
